version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - 'docker-postgres:/var/lib/postgresql/data'
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - 'docker-redis:/var/lib/redis/data'
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/taugenMotors-Backend
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    env_file:
      - .docker.env
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/taugenMotors-Backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - 'redis'
      - 'sidekiq'
    env_file:
      - .docker.env
    links:
      - db
      - redis
      - sidekiq
volumes:
  docker-postgres:
  docker-redis: